export const ANALYZER_QUEUE = "analyzer";
export const ANALYZE_ROUND_JOB = "analyze-round";
export const ANALYZE_ROUND_JOB_ATTEMPTS = 2;
export const ANALYZE_ROUND_JOB_BACKOFF_DELAY_MS = 5000;
export const ANALYZE_ROUND_JOB_BACKOFF_JITTER = 0.5;
export const ANALYZE_ROUND_DEPENDENCY_RETRY_DELAY_MS = 2000;

export const DEFAULT_MAX_COMPONENTS_PER_TURN = 10;
export const DEFAULT_MAX_FACT_CHECK_TARGETS_PER_TURN = 5;
export const DEFAULT_MAX_COMPONENT_STATEMENT_LENGTH = 1000;

export const NEW_COMPONENT_LOCAL_KEY_PATTERN = /^NEW_[1-9]\d*$/;
