export const JUDGE_ARGUMENTATION_MAX_SCORE = 40;
export const JUDGE_INTERACTION_MAX_SCORE = 30;
export const JUDGE_FACTUAL_RELIABILITY_MAX_SCORE = 30;

export const DEFAULT_MAX_JUDGE_OVERALL_REASON_LENGTH = 3000;
export const DEFAULT_MAX_JUDGE_FEEDBACK_LENGTH = 1500;
export const DEFAULT_JUDGE_PROCESSING_STALE_MS = 75000;
export const DEFAULT_JUDGE_MANUAL_RETRY_STALE_MS = 75000;

export const JUDGE_JOB_ATTEMPTS = 2;
export const JUDGE_JOB_BACKOFF_DELAY_MS = 5000;
export const JUDGE_JOB_BACKOFF_JITTER = 0.5;
export const JUDGE_RECOVERY_BATCH_SIZE = 100;
export const DEFAULT_JUDGE_RECOVERY_INTERVAL_MS = 30000;
