export const JUDGE_ARGUMENTATION_MAX_SCORE = 40;
export const JUDGE_INTERACTION_MAX_SCORE = 30;
export const JUDGE_FACTUAL_RELIABILITY_MAX_SCORE = 30;

export const DEFAULT_MAX_JUDGE_OVERALL_REASON_LENGTH = 3000;
export const DEFAULT_MAX_JUDGE_FEEDBACK_LENGTH = 1500;
