export const DEFAULT_MAX_FACT_CHECK_TARGETS_PER_BATCH = 5;
export const DEFAULT_MAX_FACT_CHECK_REASON_LENGTH = 2000;
export const DEFAULT_MAX_FACT_CHECK_SOURCES_PER_RESULT = 5;

export const FACT_CHECK_JOB_ATTEMPTS = 3;
export const FACT_CHECK_JOB_BACKOFF_DELAY_MS = 1000;
export const FACT_CHECK_RECOVERY_BATCH_SIZE = 100;
